Profiles:
    ProjectOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
#######List-Start
                    - *-OrgIDForReplace-
#######List-End
    ProjectOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
#######List-Start
                - *-OrgIDForReplace-
#######List-End
Organizations:
    - &OrdererOrg
        Name: -OrderIDForReplace-
        ID: -OrderIDForReplace-
        MSPDir: -ProjectDIR-/crypto-config/ordererOrganizations/-DomainForReplace-/msp
        AdminPrincipal: Role.ADMIN
#######List-Start
    - &-OrgIDForReplace-
        Name: -OrgIDForReplace-
        ID: -OrgIDForReplace-
        MSPDir: -ProjectDIR-/crypto-config/peerOrganizations/-OrgIDForReplace-.-DomainForReplace-/msp
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            - Host: -AnchorIpForReplace-
              Port: -AnchorPortForReplace-
#######List-End
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
#######OrderList-Start
        - -OrderIDForReplace-.-DomainForReplace-:-OrderPortForReplace-
#######OrderList-End
    BatchTimeout: 4s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 1024 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
Application: &ApplicationDefaults
    Organizations:
