version: '2'

networks:
  default:

services:

  zookeeper0.-DomainForReplace-:
    container_name: zookeeper0.-DomainForReplace-
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0.-DomainForReplace-:2888:3888 server.2=zookeeper1.-DomainForReplace-:2888:3888 server.3=zookeeper2.-DomainForReplace-:2888:3888 server.4=zookeeper3.-DomainForReplace-:2888:3888  server.5=zookeeper4.-DomainForReplace-:2888:3888
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  zookeeper1.-DomainForReplace-:
    container_name: zookeeper1.-DomainForReplace-
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0.-DomainForReplace-:2888:3888 server.2=zookeeper1.-DomainForReplace-:2888:3888 server.3=zookeeper2.-DomainForReplace-:2888:3888 server.4=zookeeper3.-DomainForReplace-:2888:3888  server.5=zookeeper4.-DomainForReplace-:2888:3888
    restart: always
    ports:
      - 2182:2181
      - 2889:2888
      - 3889:3888

  zookeeper2.-DomainForReplace-:
    container_name: zookeeper2.-DomainForReplace-
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0.-DomainForReplace-:2888:3888 server.2=zookeeper1.-DomainForReplace-:2888:3888 server.3=zookeeper2.-DomainForReplace-:2888:3888 server.4=zookeeper3.-DomainForReplace-:2888:3888  server.5=zookeeper4.-DomainForReplace-:2888:3888
    restart: always
    ports:
      - 2183:2181
      - 2890:2888
      - 3890:3888

  zookeeper3.-DomainForReplace-:
    container_name: zookeeper3.-DomainForReplace-
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=4
      - ZOO_SERVERS=server.1=zookeeper0.-DomainForReplace-:2888:3888 server.2=zookeeper1.-DomainForReplace-:2888:3888 server.3=zookeeper2.-DomainForReplace-:2888:3888 server.4=zookeeper3.-DomainForReplace-:2888:3888  server.5=zookeeper4.-DomainForReplace-:2888:3888
    restart: always
    ports:
      - 2184:2181
      - 2891:2888
      - 3891:3888
  
  zookeeper4.-DomainForReplace-:
    container_name: zookeeper4.-DomainForReplace-
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=5
      - ZOO_SERVERS=server.1=zookeeper0.-DomainForReplace-:2888:3888 server.2=zookeeper1.-DomainForReplace-:2888:3888 server.3=zookeeper2.-DomainForReplace-:2888:3888 server.4=zookeeper3.-DomainForReplace-:2888:3888  server.5=zookeeper4.-DomainForReplace-:2888:3888
    restart: always
    ports:
      - 2185:2181
      - 2892:2888
      - 3892:3888

  kafka0.-DomainForReplace-:
    container_name: kafka0.-DomainForReplace-
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.-DomainForReplace-:2181,zookeeper1.-DomainForReplace-:2181,zookeeper2.-DomainForReplace-:2181,zookeeper3.-DomainForReplace-:2181,zookeeper4.-DomainForReplace-:2181
    depends_on:
      - zookeeper0.-DomainForReplace-
      - zookeeper1.-DomainForReplace-
      - zookeeper2.-DomainForReplace-
      - zookeeper3.-DomainForReplace-
      - zookeeper4.-DomainForReplace-
    ports:
      - 9092:9092
      - 9093:9093

  kafka1.-DomainForReplace-:
    container_name: kafka1.-DomainForReplace-
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.-DomainForReplace-:2181,zookeeper1.-DomainForReplace-:2181,zookeeper2.-DomainForReplace-:2181,zookeeper3.-DomainForReplace-:2181,zookeeper4.-DomainForReplace-:2181
    depends_on:
      - zookeeper0.-DomainForReplace-
      - zookeeper1.-DomainForReplace-
      - zookeeper2.-DomainForReplace-
      - zookeeper3.-DomainForReplace-
      - zookeeper4.-DomainForReplace-
    ports:
      - 9192:9092
      - 9193:9093

  kafka2.-DomainForReplace-:
    container_name: kafka2.-DomainForReplace-
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.-DomainForReplace-:2181,zookeeper1.-DomainForReplace-:2181,zookeeper2.-DomainForReplace-:2181,zookeeper3.-DomainForReplace-:2181,zookeeper4.-DomainForReplace-:2181
    depends_on:
      - zookeeper0.-DomainForReplace-
      - zookeeper1.-DomainForReplace-
      - zookeeper2.-DomainForReplace-
      - zookeeper3.-DomainForReplace-
      - zookeeper4.-DomainForReplace-
    ports:
      - 9292:9092
      - 9293:9093

  kafka3.-DomainForReplace-:
    container_name: kafka3.-DomainForReplace-
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.-DomainForReplace-:2181,zookeeper1.-DomainForReplace-:2181,zookeeper2.-DomainForReplace-:2181,zookeeper3.-DomainForReplace-:2181,zookeeper4.-DomainForReplace-:2181
    depends_on:
      - zookeeper0.-DomainForReplace-
      - zookeeper1.-DomainForReplace-
      - zookeeper2.-DomainForReplace-
      - zookeeper3.-DomainForReplace-
      - zookeeper4.-DomainForReplace-
    ports:
      - 9392:9092
      - 9393:9093

