version: '2'

networks:
  default:

services:
  -ContainerIdForReplace-:
    container_name: -ContainerIdForReplace-
    privileged: true
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=-NetWorkForReplace-_default
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt

      - CORE_PEER_ID=-ContainerIdForReplace-
      - CORE_PEER_LOCALMSPID=-OrgIDForReplace-
      - CORE_PEER_ADDRESS=-ContainerIdForReplace-:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=-ContainerIdForReplace-:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=-ContainerIdForReplace-:7051
#########COUCH_Start
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=-CouchContainerIdForReplace-:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=-CouchUserForReplace-
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=-CouchPasswordForReplace-
#########COUCH_End
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - -PeerPortForReplace-:7051
      - -PeerEventPortForReplace-:7053
    volumes:
#########PeerList_Start
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/dubai.hlc.com/peers/peer0.dubai.hlc.com/:/etc/hyperledger/crypto/peer
      - ./channel/crypto-config/peerOrganizations/dubai.hlc.com/peers/peer0.dubai.hlc.com/msp:/etc/hyperledger/fabric/msp
      - ./channel/crypto-config/peerOrganizations/dubai.hlc.com/peers/peer0.dubai.hlc.com/tls:/etc/hyperledger/fabric/tls
#########PeerList_End

#########OrderExtra_Start  
    extra_hosts:
      - "-OrderIDForReplace-.-DomainForReplace-:-OrderIPForReplace-"
#########OrderExtra_End
#########DependOn_Start
    depends_on:
      - -CouchContainerIdForReplace-
#########DependOn_End
    networks:
      - default
      